export const fps = "/fps"
export const rpg = "/rpg"
export const zrecznosciowe = "/zręcznościowe"
export const przygodowe = "/przygodowe"
export const battle_royale = "/battle_royale"
export const symulatory = "/symulatory"
export const home = "/"